/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leet.code.solution;

import org.junit.jupiter.api.Test;

public class MainTest {

    @Test
    public void someTest() {
    }
}
